name: SukiSU Update Monitor
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:  # 新增权限声明[3](@ref)
  actions: write
  contents: read

jobs:
  check-update:
    runs-on: ubuntu-latest
    env:
      LAST_SAVED: ${{ secrets.LAST_COMMIT }}  # 使用加密存储历史值

    steps:
    - name: 获取最新提交哈希
      id: get_commit
      run: |
        LATEST_COMMIT=$(curl -s https://api.github.com/repos/ShirkNeko/SukiSU-Ultra/commits/main | jq -r '.sha')
        echo "current=$LATEST_COMMIT" >> $GITHUB_ENV

    - name: 触发主工作流
      if: env.current != env.LAST_SAVED
      uses: actions/github-script@v6
      with:
        script: |
          // 使用正确的JavaScript语法[6](@ref)
          try {
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ONEPLUS-SM8750-SuKiSu-SUSFS.yml',
              ref: 'main',
              inputs: {  // 通过inputs传递参数
                CPU: 'sm8750',
                FEIL: 'oneplus_13'
              }
            });
            console.log('工作流触发成功');
          } catch (error) {
            core.setFailed(`触发失败: ${error}`);
          }

    - name: 保存当前状态
      if: env.current != env.LAST_SAVED
      run: |
        # 将最新提交哈希写入加密Secret[3](@ref)
        echo "LAST_COMMIT=${{ env.current }}" >> $GITHUB_ENV
        gh secret set LAST_COMMIT --body "${{ env.current }}"  # 需要添加GITHUB_TOKEN权限
