name: SukiSU Update Monitor
on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时检测一次

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
    - name: 获取最新提交哈希
      id: get_commit
      run: |
        LATEST_COMMIT=$(curl -s https://api.github.com/repos/ShirkNeko/SukiSU-Ultra/commits/main | jq -r '.sha')
        echo "current=$LATEST_COMMIT" >> $GITHUB_ENV
        
    - name: 触发主工作流
      if: env.current != env.LAST_SAVED
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'ONEPLUS-SM8750-SuKiSu-SUSFS.yml', # 替换为实际工作流文件名
            ref: 'main',
            inputs: {
              CPU: 'sm8750',
              FEIL: 'oneplus_13',
              # 其他默认参数...
            }
          })
    - name: 保存当前状态
      if: env.current != env.LAST_SAVED
      run: |
        echo "LAST_SAVED=${{ env.current }}" >> $GITHUB_ENV
