name: OnePlus SM8750 AutoBuild with SukiSU Monitor (Updated)
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8750'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_13'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'sun'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.6'
      KERNEL_NAME:
        description: "修改内核名称"
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444'
      LZ4:
        type: boolean
        description: "是否启用lz4？"
        required: true
        default: 'false'
      KPM:
        type: boolean
        description: "是否启用 KPM 功能？"
        required: true
        default: 'false'
  schedule:
    - cron: '*/30 * * * *'  # 每6小时检查一次

env:
  TARGET_REPO: "ShirkNeko/SukiSU-Ultra"
  TRACKER_FILE: ".github/suki_last_commit.txt"

jobs:
  monitor:
    name: Check SukiSU Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get latest commit
        id: suki_commit
        run: |
          RESPONSE=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ env.TARGET_REPO }}/commits/main)
          
          SHA=$(jq -r '.sha' <<< "$RESPONSE")
          DATE=$(jq -r '.commit.committer.date' <<< "$RESPONSE")
          
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "CURRENT_SHA=$SHA" >> $GITHUB_ENV

      - name: Restore last commit
        id: last_commit
        uses: actions/cache@v3
        with:
          path: ${{ env.TRACKER_FILE }}
          key: suki-tracker-${{ runner.os }}

      - name: Compare commits
        id: compare
        run: |
          # 读取上次记录的commit
          if [ -f "${{ env.TRACKER_FILE }}" ]; then
            LAST_SHA=$(cat "${{ env.TRACKER_FILE }}")
            echo "last_sha=$LAST_SHA" >> $GITHUB_OUTPUT
          else
            echo "last_sha=null" >> $GITHUB_OUTPUT
          fi

          # 比较commit差异
          if [ "${{ steps.suki_commit.outputs.sha }}" != "${{ steps.compare.outputs.last_sha }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "${{ env.CURRENT_SHA }}" > "${{ env.TRACKER_FILE }}"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Save new commit
        if: steps.compare.outputs.changed == 'true'
        run: |
          echo "${{ env.CURRENT_SHA }}" > "${{ env.TRACKER_FILE }}"

  build:
    name: Build Kernel
    needs: monitor
    if: needs.monitor.outputs.changed == 'true'
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git
        run: |
          git config --global user.name "build"
          git config --global user.email "wuzikh@163.com"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl jq

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/JiuGeFaCai/kernel_manifest.git \
            -b refs/heads/oneplus/${{ inputs.CPU || 'sm8750' }} \
            -m ${{ inputs.FEIL || 'oneplus_13' }}.xml --depth=1
          repo --trace sync -c -j$(nproc --all) --no-tags
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"

      - name: Set up SukiSU
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
          cd ./KernelSU
          KSU_VERSION=$(expr $(git rev-list --count main) "+" 10606)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: Set up susfs
        run: |
          cd kernel_workspace
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION || 'android15' }}-${{ inputs.KERNEL_VERSION || '6.6' }}
          git clone https://github.com/ExmikoN/SukiSU_patch.git

          cd kernel_platform        
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION || 'android15' }}-${{ inputs.KERNEL_VERSION || '6.6' }}.patch ./common/
          cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          cp -r ../SukiSU_patch/other/lz4k/include/linux/* ./common/include/linux
          cp -r ../SukiSU_patch/other/lz4k/lib/* ./common/lib
          cp -r ../SukiSU_patch/other/lz4k/crypto/* ./common/crypto
          cd ./common
          sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION || 'android15' }}-${{ inputs.KERNEL_VERSION || '6.6' }}.patch
          sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION || 'android15' }}-${{ inputs.KERNEL_VERSION || '6.6' }}.patch
          patch -p1 < 50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION || 'android15' }}-${{ inputs.KERNEL_VERSION || '6.6' }}.patch || true
          cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
          patch -p1 -F 3 < syscall_hooks.patch

      - name: Apply Hide Stuff Patches
        run: |
          cd kernel_workspace/kernel_platform/common
          cp ../../SukiSU_patch/69_hide_stuff.patch ./
          patch -p1 -F 3 < 69_hide_stuff.patch

      - name: Apply lz4kd Patches
        if: ${{ inputs.LZ4 == 'true' }}
        run: |
          cd kernel_workspace/kernel_platform/common
          cp ../../SukiSU_patch/other/lz4k_patch/${{ inputs.KERNEL_VERSION || '6.6' }}/lz4kd.patch ./
          patch -p1 -F 3 < lz4kd.patch || true

      - name: Add SUSFS Configuration Settings
        run: |
          cd kernel_workspace/kernel_platform
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [ "${{ inputs.KPM }}" = "true" ]; then
            echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          cd common
          git add -A && git commit -a -m "BUILD Kernel"

      - name: Add make name
        run: |
          cd kernel_workspace/kernel_platform
          sed -i 's/res="\$res\$(cat "\$file")"/res="${{ inputs.KERNEL_NAME || '-android15-8-g013ec21bba94-abogki383916444' }}"/g' ./common/scripts/setlocalversion

      - name: Build kernel
        run: |
          cd kernel_workspace/kernel_platform
          tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist

      - name: Patch Kernel Image
        run: |
          cd kernel_workspace/kernel_platform/dist/
          curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
          chmod +x patch_linux
          ./patch_linux
          rm -f Image
          mv oImage Image

      - name: Prepare AnyKernel3
        run: |
          cd kernel_workspace/kernel_platform/dist/
          if [ "${{ inputs.FEIL || 'oneplus_13' }}" = "oneplus_ace5_pro" ]; then
            git clone -b a5p https://github.com/JiuGeFaCai/AnyKernel3.git --depth=1
          else
            git clone https://github.com/JiuGeFaCai/AnyKernel3.git --depth=1
          fi
          rm -rf ./AnyKernel3/.git
          rm -rf ./AnyKernel3/push.sh
          cp Image ./AnyKernel3/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SuKiSu_${{ inputs.LZ4 == 'true' && 'LZ4' || 'NoLZ4' }}_${{ inputs.KPM == 'true' && 'KPM' || 'NoKPM' }}_${{ env.KSUVER }}_${{ inputs.FEIL || 'oneplus_13' }}
          path: |
            kernel_workspace/kernel_platform/dist/AnyKernel3/*
            kernel_workspace/kernel_platform/dist/Image
          retention-days: 7
